package hw1;
import java.io.FileNotFoundException;

/**
 * @author Aleksandar Brestovski
 * Written: 12/02/2026
 * 
 * Represents a Markov source model trained on a text corpus.
 * 
 * The model computes transition probabilities between letters (a–z)
 * using Markov model and can estimate the probability
 * that a given test string was generated by the model.
 */

public class SourceModel {
	
	private int[][] matrixCounts;
	private double[][] matrixProbabilities;
	private String name;
	private String filename;
	
	/**
	 * Deafualt Constructor for {@link SourceModel}.
	 */
	
	public SourceModel() {}
	
	/**
     * Constructs and trains a {@link SourceModel} using a corpus file.
     * 
     * The constructor reads the training text, builds the transition
     * count matrix, and converts it into a probability matrix.
     *
     * @param filename the name of the corpus file.
     * @param name the name of the source model.
     * @throws FileNotFoundException if the corpus file cannot be found.
     */
	
	public SourceModel(String filename, String name) throws FileNotFoundException {
		this.name = name;
		this.filename = filename;
		ReadFile rf = new ReadFile();
		MatrixCounts mc = new MatrixCounts();
		MatrixProbabilities mp = new MatrixProbabilities();

		System.out.print("Training " + this.name + " model ... ");
		
		char[] data = rf.readFile(this.filename);
		
		this.matrixCounts = mc.createMatrixCounts(data);
		
		this.matrixProbabilities = mp.createMatrixProbabilities(matrixCounts);

		System.out.println("done.");

	}

	 /**
     * Returns the name of the source model.
     *
     * @return the model name.
     */
	
	public String getName() {
		return this.name;
	}
	
	/**
     * Computes the probability that a test string was generated
     * by this {@link SourceModel}.
     * 
     * Only lowercase alphabetic characters are considered, and the
     * probability is computed as the product of transition probabilities
     * for each consecutive character pair.
     *
     * @param test the test string to evaluate.
     * @return the probability of the string, or -1.0 if invalid.
     */
	
	public double probability(String test) {
		if(test == null || test.length( ) < 2) 
			return -1.0;
			
			double probability = 1.0;
			String newtest = test.toLowerCase();
			char[] validChars = new char[newtest.length()];
			int validCount = 0;
		
			for(int i = 0; i < newtest.length(); i++) {
				if(newtest.charAt(i) >= 'a' && newtest.charAt(i) <= 'z') {
					validChars[validCount] = newtest.charAt(i);
					validCount++;
				}
			}
			
			if(validCount < 2)
				return -1.0;
		
			for(int i = 0; i < validCount - 1; i++) {
					probability *= matrixProbabilities[validChars[i] - 'a'][validChars[i + 1] - 'a'];
			}
			
			return probability;
	}
	
	/**
     * Returns a formatted string describing the probability output
     * for this {@link SourceModel}.
     *
     * @return a string representation of the model's probability output.
     */

	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Probability that test string is ");
		sb.append(this.getName());
		sb.append(": ");
		
		return sb.toString();
	}
	
	/**
     * Main method for executing the program from the command line.
     * 
     * The program trains a SourceModel for each corpus file provided
     * and determines which model most likely generated the test string.
     *
     * @param args command-line arguments containing corpus files
     *             followed by a test string.
     * @throws FileNotFoundException if any corpus file cannot be found.
     */

	public static void main(String[] args) throws FileNotFoundException {
        String text = args[args.length - 1];
        String[] name = new String[args.length - 1];
        SourceModel[] sm = new SourceModel[args.length - 1];
        
        
        for (int i = 0; i < args.length - 1; i++) {
            name[i] = args[i].substring(0, args[i].indexOf("."));
        	
        	sm[i] = new SourceModel(args[i], name[i]);
        	
        	if(sm[i].probability(text) < 0)
        		System.out.println("No text given. Give text with characters in it.");
        }
    
        System.out.println("Analyzing: " + text);
        
        double sumOfProbabilities = 0.0;
        
        for(int i = 0; i < sm.length; i++) {
        	sumOfProbabilities += sm[i].probability(text);
        }
        
        for (int i = 0; i < args.length - 1; i++) {
        	System.out.printf(sm[i] + "%.2f",(sm[i].probability(text) / sumOfProbabilities));
        	System.out.println();
        }
        
        double max = -1;
        double prob = -1;
        String best = "";
        
        for(int i = 0; i < sm.length; i++) {
        	prob = sm[i].probability(text);
        	if(prob > max) {
        		max = prob;
        		best = sm[i].getName();
        	}
        }
        
        System.out.println("Test string is most likely " + best + ".");
     
    }
}

